[package]
name = "PlanSync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }  # Add serde feature
colored = "2.0"
dialoguer = "0.11"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
